name: Geya
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0=openblas
  - blosc=1.21.3=h313beb8_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli-python=1.0.9=py312h313beb8_9
  - brotlicffi=1.0.9.2=py312h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2026.01.04=py312hca03da5_0
  - cffi=2.0.0=py312h73c2a22_1
  - cfitsio=3.470=h7f6438f_7
  - charset-normalizer=3.4.4=py312hca03da5_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - docopt=0.6.2=py312hca03da5_1
  - expat=2.6.4=h313beb8_0
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.55.3=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - freexl=2.0.0=ha3de405_0
  - gdal=3.6.2=py312h5ed0132_9
  - geos=3.10.6=h313beb8_0
  - geotiff=1.7.0=h41f0982_3
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - icu=73.1=h313beb8_0
  - idna=3.11=py312hca03da5_0
  - joblib=1.4.2=py312hca03da5_0
  - jpeg=9e=h80987f9_3
  - json-c=0.16=h1a28f6b_0
  - kealib=1.5.0=hba2eb73_1
  - kiwisolver=1.4.8=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libboost=1.82.0=h0bc93f9_2
  - libcurl=8.12.1=hde089ae_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgdal=3.6.2=h0e880fd_9
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libkml=1.3.0=hc4d7c42_7
  - libmpdec=4.0.0=h80987f9_0
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=17.4=h02f6b3c_0
  - libspatialite=5.1.0=h4e90699_2
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.5=h0b34f26_0
  - libzip=1.8.0=h62fee54_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.0=py312hca03da5_0
  - matplotlib-base=3.10.0=py312h7ef442a_0
  - minizip=4.0.3=ha89c15f_0
  - ncurses=6.4=h313beb8_0
  - nspr=4.35=h313beb8_0
  - nss=3.89.1=h313beb8_0
  - numexpr=2.10.1=py312h5d9532f_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h54b8e55_0
  - openldap=2.6.4=he7ef289_0
  - openssl=3.4.1=h81ee809_0
  - packaging=24.2=py312hca03da5_0
  - pandas=2.2.3=py312hcf29cfe_0
  - pcre2=10.42=hb066dcc_1
  - pillow=11.1.0=py312h84e58ab_0
  - pip=25.0=py312hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - poppler=24.09.0=h092caa6_1
  - poppler-data=0.4.11=hca03da5_1
  - proj=9.3.1=h805f6d4_0
  - pycparser=2.23=py312hca03da5_0
  - pyparsing=3.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.9=h99e199e_0
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312hca03da5_0
  - qhull=2020.2=h48ca7d4_2
  - readline=8.2=h1a28f6b_0
  - requests=2.32.5=py312hca03da5_1
  - scikit-learn=1.6.1=py312h313beb8_0
  - scipy=1.15.2=py312h14fe6a6_1
  - setuptools=72.1.0=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h80987f9_0
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tiledb=2.3.3=hb4a6b97_3
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py312h80987f9_0
  - tqdm=4.67.1=py312h989b03a_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_1
  - uriparser=0.9.7=h80987f9_0
  - urllib3=2.5.0=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - xerces-c=3.2.4=h313beb8_1
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - aiofiles==24.1.0
      - aiogram==3.20.0.post0
      - annotated-types==0.7.0
      - backcall==0.2.0
      - filelock==3.20.0
      - fsspec==2025.10.0
      - imageio==2.37.0
      - ipython==8.12.3
      - lazy-loader==0.4
      - magic-filter==1.0.12
      - mpmath==1.3.0
      - networkx==3.5
      - pipreqs==0.5.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - scikit-image==0.25.2
      - sympy==1.14.0
      - tifffile==2025.9.20
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - typing-inspection==0.4.0
      - yarg==0.1.9
prefix: /opt/homebrew/anaconda3/envs/Geya
